---
- name: enable overcommit in sysctl
  sysctl:
    name: vm.overcommit_memory
    value: "1"
    state: present
    reload: yes
    ignoreerrors: yes

- name: Set somaxconn
  sysctl:
    name: net.core.somaxconn
    value: "512"
    state: present
    reload: yes
    ignoreerrors: yes

- name: Install server and sentinel
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - redis-server
    - redis-sentinel


